// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWlx7340zHxnVCXTVAQb9c5hymh1yERLk',
    appId: '1:754277003448:web:de984e3e2f27db8231044d',
    messagingSenderId: '754277003448',
    projectId: 'moscare-dev',
    authDomain: 'moscare-dev.firebaseapp.com',
    storageBucket: 'moscare-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB2-ZQlFvQSFv37wfg-wvWK-mZe9fWiu0',
    appId: '1:754277003448:android:27d0e5efee2e269e31044d',
    messagingSenderId: '754277003448',
    projectId: 'moscare-dev',
    storageBucket: 'moscare-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxtACk_vbVxxcL2MTMV95hrth-yqUc1s',
    appId: '1:754277003448:ios:2669aa6b5060952e31044d',
    messagingSenderId: '754277003448',
    projectId: 'moscare-dev',
    storageBucket: 'moscare-dev.appspot.com',
    iosBundleId: 'com.lamaq.aqMoscare',
  );

}